return {
  heading = {
    challenge = 'CHALLENGE',
    completion = 'COMPLETION',
    date = 'DATE',
    player = 'PLAYER',
    requirements = 'REQUIREMENTS',
    result = 'RESULT',
  },
  charts = {
    bpm = 'BPM',
    clear = 'CLEAR',
    completion = 'COMPLETION',
    critical = 'CRITICAL',
    difficulty = 'DIFFICULTY',
    error = 'ERROR',
    gauge = 'GAUGE',
    grade = 'GRADE',
    maxChain = 'MAX CHAIN',
    near = 'NEAR',
    result = 'RESULT',
    score = 'SCORE',
    title = 'TITLE',
  },
};