return {
  '1. CLOSE SETTINGS WINDOW',
  '2. SCRUB THROUGH SONG TO FIND START POINT',
  '3. OPEN SETTINGS WINDOW',
  '4. [GENERAL]  SELECT "USE CURRENT TIME AS START POINT"',
  '5. REPEAT STEPS 1-4 FOR END POINT',
  '6. [GENERAL]  ENABLE "AUTO-RESTART ON PASS"',
  '7. [GENERAL]  ENABLE "AUTO-RESTART ON FAIL"',
  '8. [MISSION SETTINGS]  SET "FAIL CONDITION"',
  '9. [MAIN]  SELECT "BEGIN PRACTICE"',
};