---@meta

---
---`Score` object.  
---[Official Documentation](https://unnamed-sdvx-clone.readthedocs.io/en/latest/songwheel.html#score)
---
---@class Score
---
---@field auto_flags autoFlags
---
---@field badge badge
---
---@field gauge gaugeValue
---
---@field gauge_option gaugeOption
---
---@field gauge_type gaugeType
---
---@field goods integer # The total near count.
---
---@field hitWindow HitWindow
---
---@field mirror mirror
---
---@field misses integer # The total error count.
---
---@field name playerName # Only available for `Multiplayer`.
---
---@field perfects integer # The total critical count.
---
---@field random random
---
---@field score score
---
---@field timestamp timestamp
---
